# Generated by Django 6.0.4 on 2026-04-11 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Licenciatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('abreviatura', models.CharField(max_length=5)),
                ('universidade', models.CharField(max_length=100)),
                ('duracao_anos', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('areas', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=250)),
                ('rating', models.IntegerField()),
                ('autores', models.CharField(max_length=200)),
                ('orientadores', models.CharField(max_length=200)),
                ('tecnologias', models.CharField(max_length=200)),
                ('areas', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='tfcs/')),
            ],
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=250)),
                ('data', models.DateField()),
                ('competencias', models.ManyToManyField(related_name='formacao', to='portfolio.competencia')),
            ],
        ),
        migrations.CreateModel(
            name='ContribuicaoOpenSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=100)),
                ('descricao_projeto', models.CharField(max_length=250)),
                ('descricao_contribuicao', models.CharField(max_length=500)),
                ('link_repo', models.CharField(max_length=250)),
                ('tecnologia', models.ManyToManyField(to='portfolio.tecnologia')),
            ],
        ),
        migrations.CreateModel(
            name='UC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('abreviatura', models.CharField(max_length=5)),
                ('semestre', models.CharField(max_length=1)),
                ('ano', models.IntegerField()),
                ('licenciatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.licenciatura')),
            ],
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='unidade_curriculares',
            field=models.ManyToManyField(null=True, related_name='tecnologias_usadas', to='portfolio.uc'),
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=250)),
                ('competencia', models.ManyToManyField(related_name='projeto', to='portfolio.competencia')),
                ('tecnologias', models.ManyToManyField(to='portfolio.tecnologia')),
                ('unidade_curricular', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.uc')),
            ],
        ),
    ]
