# Generated by Django 6.0.4 on 2026-04-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfc',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='tfcs/'),
        ),
        migrations.AddField(
            model_name='tfc',
            name='keyWords',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='unidade_curriculares',
            field=models.ManyToManyField(related_name='tecnologias_usadas', to='portfolio.uc'),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='descricao',
            field=models.TextField(),
        ),
    ]
