# Generated by Django 6.0.4 on 2026-05-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_tfc_imagem_tfc_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='unidade_curricular',
        ),
        migrations.AddField(
            model_name='projeto',
            name='unidade_curricular',
            field=models.ManyToManyField(to='portfolio.uc'),
        ),
    ]
