# Generated by Django 6.0.4 on 2026-05-04 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_projeto_unidade_curricular_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='unidade_curricular',
        ),
        migrations.AddField(
            model_name='projeto',
            name='unidade_curricular',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.uc'),
        ),
    ]
