# Generated by Django 6.0.4 on 2026-05-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0002_artigo_likes_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='autor',
            field=models.CharField(),
        ),
    ]
